import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { Plus, Search, FileText, Trash2, BookOpen, X } from 'lucide-react';
import { Note, Subject } from '@/types';
import { motion, AnimatePresence } from 'motion/react';
import { cn } from '@/lib/utils';

interface NotebookProps {
  notes: Note[];
  setNotes: React.Dispatch<React.SetStateAction<Note[]>>;
  selectedNoteId: string | null;
  setSelectedNoteId: (id: string | null) => void;
  setActiveTab: (tab: string) => void;
  setAssistantMode: (mode: string) => void;
  filterSubject: string | null;
  setFilterSubject: (subject: string | null) => void;
}

export function Notebook({
  notes,
  setNotes,
  selectedNoteId,
  setSelectedNoteId,
  setActiveTab,
  setAssistantMode,
  filterSubject,
  setFilterSubject
}: NotebookProps) {
  const [isAdding, setIsAdding] = useState(false);
  const [newNote, setNewNote] = useState({ title: '', content: '', subject: 'Science' as Subject });
  const [searchTerm, setSearchTerm] = useState('');

  const selectedNote = notes.find(n => n.id === selectedNoteId) || null;

  const handleAddNote = () => {
    if (newNote.title && newNote.content) {
      const note: Note = {
        id: Math.random().toString(36).substring(2, 9),
        title: newNote.title,
        content: newNote.content,
        subject: newNote.subject,
        createdAt: Date.now()
      };
      setNotes([note, ...notes]);
      setSelectedNoteId(note.id); // Automatically select new note
      setNewNote({ title: '', content: '', subject: 'Science' });
      setIsAdding(false);
    }
  };

  const deleteNote = (id: string) => {
    if (confirm('Are you sure you want to delete this note?')) {
      setNotes(notes.filter(n => n.id !== id));
      if (selectedNoteId === id) setSelectedNoteId(null);
    }
  };

  const handleStudyWithAI = (note: Note) => {
    setSelectedNoteId(note.id);
    setAssistantMode('chat');
    setActiveTab('assistant');
  };

  const handleExportPDF = (note: Note) => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>${note.title} - BoardPrep Study Material</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                line-height: 1.6;
                color: #334155;
                padding: 40px;
                max-width: 800px;
                margin: 0 auto;
              }
              .header {
                border-bottom: 2px solid #0284c7;
                padding-bottom: 16px;
                margin-bottom: 24px;
              }
              .subject-badge {
                display: inline-block;
                background-color: #f0f9ff;
                color: #0369a1;
                font-weight: 700;
                font-size: 12px;
                text-transform: uppercase;
                letter-spacing: 0.05em;
                padding: 4px 12px;
                border-radius: 9999px;
                margin-bottom: 8px;
              }
              h1 {
                font-size: 32px;
                color: #0f172a;
                margin: 0 0 8px 0;
              }
              .meta {
                font-size: 13px;
                color: #94a3b8;
              }
              .content {
                font-size: 16px;
                white-space: pre-wrap;
              }
              .footer {
                margin-top: 48px;
                border-top: 1px solid #e2e8f0;
                padding-top: 16px;
                text-align: center;
                font-size: 12px;
                color: #94a3b8;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <span class="subject-badge">${note.subject}</span>
              <h1>${note.title}</h1>
              <div class="meta">Created on: ${new Date(note.createdAt).toLocaleDateString()} | BoardPrep AI Study Companion</div>
            </div>
            <div class="content">${note.content}</div>
            <div class="footer">
              Generated by BoardPrep AI Assistant - CBSE/ICSE Personalized Class 10 Prep
            </div>
            <script>
              window.onload = function() {
                window.print();
                window.close();
              }
            </script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  };

  const filteredNotes = notes.filter(note => {
    const matchesSearch = note.title.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          note.content.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesSubject = filterSubject ? note.subject === filterSubject : true;
    return matchesSearch && matchesSubject;
  });

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 h-[calc(100vh-12rem)]">
      {/* Sidebar: Notes List */}
      <div className="lg:col-span-1 flex flex-col gap-4">
        <div className="flex items-center justify-between">
          <h3 className="text-xl font-bold text-slate-800">My Notes</h3>
          <Button onClick={() => setIsAdding(true)} size="sm" className="bg-brand-600 hover:bg-brand-700 cursor-pointer">
            <Plus className="w-4 h-4 mr-2" /> New Note
          </Button>
        </div>

        {/* Filter badge if subject filter active */}
        {filterSubject && (
          <div className="flex items-center justify-between bg-brand-50 border border-brand-200 px-3 py-2 rounded-xl text-xs text-brand-700">
            <span>Filtered by: <strong className="font-bold">{filterSubject}</strong></span>
            <button 
              type="button" 
              onClick={() => setFilterSubject(null)}
              className="text-brand-500 hover:text-brand-700 cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        )}

        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <Input 
            placeholder="Search notes..." 
            className="pl-10 bg-white border-slate-200" 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>

        <ScrollArea className="flex-1 pr-4">
          <div className="space-y-3">
            {filteredNotes.length > 0 ? (
              filteredNotes.map((note) => (
                <Card 
                  key={note.id} 
                  className={cn(
                    "cursor-pointer transition-all border-none shadow-sm hover:shadow-md",
                    selectedNoteId === note.id ? "ring-2 ring-brand-500 bg-brand-50/50" : "bg-white"
                  )}
                  onClick={() => {
                    setSelectedNoteId(note.id);
                    setIsAdding(false);
                  }}
                >
                  <CardHeader className="p-4">
                    <div className="flex justify-between items-start">
                      <Badge variant="outline" className="text-[10px] uppercase tracking-wider font-bold text-slate-500 mb-2">
                        {note.subject}
                      </Badge>
                      <Button 
                        variant="ghost" 
                        size="icon" 
                        className="h-6 w-6 text-slate-300 hover:text-red-500 cursor-pointer"
                        onClick={(e) => { e.stopPropagation(); deleteNote(note.id); }}
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </Button>
                    </div>
                    <CardTitle className="text-sm font-bold text-slate-800 line-clamp-1">{note.title}</CardTitle>
                  </CardHeader>
                </Card>
              ))
            ) : (
              <div className="text-center py-8 text-slate-400 text-sm">
                No notes found.
              </div>
            )}
          </div>
        </ScrollArea>
      </div>

      {/* Editor/Reader Pane */}
      <div className="lg:col-span-2 bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden flex flex-col">
        <AnimatePresence mode="wait">
          {isAdding ? (
            <motion.div 
              key="add-form"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="p-8 space-y-6 overflow-y-auto flex-1"
            >
              <div className="flex justify-between items-center">
                <h3 className="text-2xl font-bold text-slate-800">Create New Note</h3>
                <Button variant="ghost" onClick={() => setIsAdding(false)} className="cursor-pointer">Cancel</Button>
              </div>
              <div className="space-y-4">
                <div className="space-y-2">
                  <label className="text-sm font-semibold text-slate-600">Subject</label>
                  <div className="flex flex-wrap gap-2">
                    {['Science', 'Mathematics', 'Social Science', 'English'].map((s) => (
                      <Badge
                        key={s}
                        variant={newNote.subject === s ? 'default' : 'outline'}
                        className="cursor-pointer px-4 py-1.5 text-xs"
                        onClick={() => setNewNote({ ...newNote, subject: s as Subject })}
                      >
                        {s}
                      </Badge>
                    ))}
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-semibold text-slate-600">Title</label>
                  <Input 
                    placeholder="e.g. Newton's Third Law" 
                    value={newNote.title}
                    onChange={(e) => setNewNote({ ...newNote, title: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-semibold text-slate-600">Content</label>
                  <Textarea 
                    placeholder="Paste your textbook content or write your notes here..." 
                    className="min-h-[250px]"
                    value={newNote.content}
                    onChange={(e) => setNewNote({ ...newNote, content: e.target.value })}
                  />
                </div>
                <Button className="w-full bg-brand-600 hover:bg-brand-700 h-12 text-lg cursor-pointer" onClick={handleAddNote}>
                  Save Note
                </Button>
              </div>
            </motion.div>
          ) : selectedNote ? (
            <motion.div 
              key="view-note"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex flex-col h-full"
            >
              <div className="p-8 border-b border-slate-100 bg-slate-50/50">
                <Badge className="mb-4 bg-brand-100 text-brand-700 hover:bg-brand-100">{selectedNote.subject}</Badge>
                <h3 className="text-3xl font-bold text-slate-900">{selectedNote.title}</h3>
                <p className="text-slate-400 text-sm mt-2">Last updated: {new Date(selectedNote.createdAt).toLocaleDateString()}</p>
              </div>
              <ScrollArea className="flex-1 p-8">
                <div className="prose prose-slate max-w-none">
                  {selectedNote.content.split('\n').map((para, i) => (
                    <p key={i} className="text-slate-700 leading-relaxed mb-4">{para}</p>
                  ))}
                </div>
              </ScrollArea>
              <div className="p-6 bg-slate-50 border-t border-slate-100 flex gap-4">
                <Button 
                  variant="outline" 
                  className="flex-1 gap-2 cursor-pointer"
                  onClick={() => handleExportPDF(selectedNote)}
                >
                  <FileText className="w-4 h-4" /> Export as PDF
                </Button>
                <Button 
                  className="flex-1 gap-2 bg-brand-600 hover:bg-brand-700 cursor-pointer"
                  onClick={() => handleStudyWithAI(selectedNote)}
                >
                  <BookOpen className="w-4 h-4" /> Study with AI
                </Button>
              </div>
            </motion.div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-center p-8 text-slate-400">
              <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mb-4">
                <BookOpen className="w-10 h-10 text-slate-200" />
              </div>
              <h3 className="text-lg font-semibold text-slate-600">No Note Selected</h3>
              <p className="max-w-xs mt-2">Select a note from the sidebar or create a new one to start studying.</p>
            </div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
